CREATE TABLE IF NOT EXISTS teams (
    team_name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(100) PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    team_name VARCHAR(100) REFERENCES teams(team_name) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pull_requests (
    pr_id VARCHAR(100) PRIMARY KEY,
    pr_name VARCHAR(100) NOT NULL,
    author_id VARCHAR(100) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT NOW(),
    merged_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviewers (
    pr_id VARCHAR(100) NOT NULL REFERENCES pull_requests(pr_id) ON DELETE CASCADE,
    reviewer_id VARCHAR(100) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (pr_id, reviewer_id)
);
