// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "mPR/internal/pkg/storage/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsers is an autogenerated mock type for the Users type
type MockUsers struct {
	mock.Mock
}

type MockUsers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsers) EXPECT() *MockUsers_Expecter {
	return &MockUsers_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function with given fields: ctx, teamName, members
func (_m *MockUsers) CreateOrUpdate(ctx context.Context, teamName string, members []models.Users) error {
	ret := _m.Called(ctx, teamName, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []models.Users) error); ok {
		r0 = rf(ctx, teamName, members)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsers_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockUsers_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - members []models.Users
func (_e *MockUsers_Expecter) CreateOrUpdate(ctx interface{}, teamName interface{}, members interface{}) *MockUsers_CreateOrUpdate_Call {
	return &MockUsers_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, teamName, members)}
}

func (_c *MockUsers_CreateOrUpdate_Call) Run(run func(ctx context.Context, teamName string, members []models.Users)) *MockUsers_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]models.Users))
	})
	return _c
}

func (_c *MockUsers_CreateOrUpdate_Call) Return(_a0 error) *MockUsers_CreateOrUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsers_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, string, []models.Users) error) *MockUsers_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByTeam provides a mock function with given fields: ctx, team
func (_m *MockUsers) GetActiveByTeam(ctx context.Context, team string) ([]models.Users, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByTeam")
	}

	var r0 []models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Users, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Users); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Users)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsers_GetActiveByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByTeam'
type MockUsers_GetActiveByTeam_Call struct {
	*mock.Call
}

// GetActiveByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
func (_e *MockUsers_Expecter) GetActiveByTeam(ctx interface{}, team interface{}) *MockUsers_GetActiveByTeam_Call {
	return &MockUsers_GetActiveByTeam_Call{Call: _e.mock.On("GetActiveByTeam", ctx, team)}
}

func (_c *MockUsers_GetActiveByTeam_Call) Run(run func(ctx context.Context, team string)) *MockUsers_GetActiveByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsers_GetActiveByTeam_Call) Return(_a0 []models.Users, _a1 error) *MockUsers_GetActiveByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsers_GetActiveByTeam_Call) RunAndReturn(run func(context.Context, string) ([]models.Users, error)) *MockUsers_GetActiveByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUsers) GetByID(ctx context.Context, id uuid.UUID) (*models.Users, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Users, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Users); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Users)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsers_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUsers_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsers_Expecter) GetByID(ctx interface{}, id interface{}) *MockUsers_GetByID_Call {
	return &MockUsers_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUsers_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsers_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsers_GetByID_Call) Return(_a0 *models.Users, _a1 error) *MockUsers_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsers_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Users, error)) *MockUsers_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIsActive provides a mock function with given fields: ctx, id, active
func (_m *MockUsers) UpdateIsActive(ctx context.Context, id uuid.UUID, active bool) error {
	ret := _m.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIsActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, active)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsers_UpdateIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsActive'
type MockUsers_UpdateIsActive_Call struct {
	*mock.Call
}

// UpdateIsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - active bool
func (_e *MockUsers_Expecter) UpdateIsActive(ctx interface{}, id interface{}, active interface{}) *MockUsers_UpdateIsActive_Call {
	return &MockUsers_UpdateIsActive_Call{Call: _e.mock.On("UpdateIsActive", ctx, id, active)}
}

func (_c *MockUsers_UpdateIsActive_Call) Run(run func(ctx context.Context, id uuid.UUID, active bool)) *MockUsers_UpdateIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockUsers_UpdateIsActive_Call) Return(_a0 error) *MockUsers_UpdateIsActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsers_UpdateIsActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockUsers_UpdateIsActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsers creates a new instance of MockUsers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsers {
	mock := &MockUsers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
