// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "mPR/internal/pkg/storage/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockReviewers is an autogenerated mock type for the Reviewers type
type MockReviewers struct {
	mock.Mock
}

type MockReviewers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewers) EXPECT() *MockReviewers_Expecter {
	return &MockReviewers_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, list
func (_m *MockReviewers) Add(ctx context.Context, list []models.Reviewers) error {
	ret := _m.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Reviewers) error); ok {
		r0 = rf(ctx, list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewers_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockReviewers_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - list []models.Reviewers
func (_e *MockReviewers_Expecter) Add(ctx interface{}, list interface{}) *MockReviewers_Add_Call {
	return &MockReviewers_Add_Call{Call: _e.mock.On("Add", ctx, list)}
}

func (_c *MockReviewers_Add_Call) Run(run func(ctx context.Context, list []models.Reviewers)) *MockReviewers_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Reviewers))
	})
	return _c
}

func (_c *MockReviewers_Add_Call) Return(_a0 error) *MockReviewers_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewers_Add_Call) RunAndReturn(run func(context.Context, []models.Reviewers) error) *MockReviewers_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddOne provides a mock function with given fields: ctx, prID, reviewerID
func (_m *MockReviewers) AddOne(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for AddOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewers_AddOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOne'
type MockReviewers_AddOne_Call struct {
	*mock.Call
}

// AddOne is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - reviewerID uuid.UUID
func (_e *MockReviewers_Expecter) AddOne(ctx interface{}, prID interface{}, reviewerID interface{}) *MockReviewers_AddOne_Call {
	return &MockReviewers_AddOne_Call{Call: _e.mock.On("AddOne", ctx, prID, reviewerID)}
}

func (_c *MockReviewers_AddOne_Call) Run(run func(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID)) *MockReviewers_AddOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewers_AddOne_Call) Return(_a0 error) *MockReviewers_AddOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewers_AddOne_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockReviewers_AddOne_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, prID, reviewerID
func (_m *MockReviewers) Delete(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewers_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReviewers_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - reviewerID uuid.UUID
func (_e *MockReviewers_Expecter) Delete(ctx interface{}, prID interface{}, reviewerID interface{}) *MockReviewers_Delete_Call {
	return &MockReviewers_Delete_Call{Call: _e.mock.On("Delete", ctx, prID, reviewerID)}
}

func (_c *MockReviewers_Delete_Call) Run(run func(ctx context.Context, prID uuid.UUID, reviewerID uuid.UUID)) *MockReviewers_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewers_Delete_Call) Return(_a0 error) *MockReviewers_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewers_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockReviewers_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPR provides a mock function with given fields: ctx, prID
func (_m *MockReviewers) GetByPR(ctx context.Context, prID uuid.UUID) ([]models.Reviewers, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPR")
	}

	var r0 []models.Reviewers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Reviewers, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Reviewers); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reviewers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewers_GetByPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPR'
type MockReviewers_GetByPR_Call struct {
	*mock.Call
}

// GetByPR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
func (_e *MockReviewers_Expecter) GetByPR(ctx interface{}, prID interface{}) *MockReviewers_GetByPR_Call {
	return &MockReviewers_GetByPR_Call{Call: _e.mock.On("GetByPR", ctx, prID)}
}

func (_c *MockReviewers_GetByPR_Call) Run(run func(ctx context.Context, prID uuid.UUID)) *MockReviewers_GetByPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewers_GetByPR_Call) Return(_a0 []models.Reviewers, _a1 error) *MockReviewers_GetByPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewers_GetByPR_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Reviewers, error)) *MockReviewers_GetByPR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRsByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *MockReviewers) GetPRsByReviewer(ctx context.Context, reviewerID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsByReviewer")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewers_GetPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsByReviewer'
type MockReviewers_GetPRsByReviewer_Call struct {
	*mock.Call
}

// GetPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID uuid.UUID
func (_e *MockReviewers_Expecter) GetPRsByReviewer(ctx interface{}, reviewerID interface{}) *MockReviewers_GetPRsByReviewer_Call {
	return &MockReviewers_GetPRsByReviewer_Call{Call: _e.mock.On("GetPRsByReviewer", ctx, reviewerID)}
}

func (_c *MockReviewers_GetPRsByReviewer_Call) Run(run func(ctx context.Context, reviewerID uuid.UUID)) *MockReviewers_GetPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewers_GetPRsByReviewer_Call) Return(_a0 []uuid.UUID, _a1 error) *MockReviewers_GetPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewers_GetPRsByReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockReviewers_GetPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewers creates a new instance of MockReviewers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewers {
	mock := &MockReviewers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
