// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "mPR/internal/pkg/storage/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPullRequests is an autogenerated mock type for the PullRequests type
type MockPullRequests struct {
	mock.Mock
}

type MockPullRequests_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequests) EXPECT() *MockPullRequests_Expecter {
	return &MockPullRequests_Expecter{mock: &_m.Mock}
}

// AddReviewers provides a mock function with given fields: ctx, reviewers
func (_m *MockPullRequests) AddReviewers(ctx context.Context, reviewers []models.Reviewers) error {
	ret := _m.Called(ctx, reviewers)

	if len(ret) == 0 {
		panic("no return value specified for AddReviewers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Reviewers) error); ok {
		r0 = rf(ctx, reviewers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPullRequests_AddReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReviewers'
type MockPullRequests_AddReviewers_Call struct {
	*mock.Call
}

// AddReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewers []models.Reviewers
func (_e *MockPullRequests_Expecter) AddReviewers(ctx interface{}, reviewers interface{}) *MockPullRequests_AddReviewers_Call {
	return &MockPullRequests_AddReviewers_Call{Call: _e.mock.On("AddReviewers", ctx, reviewers)}
}

func (_c *MockPullRequests_AddReviewers_Call) Run(run func(ctx context.Context, reviewers []models.Reviewers)) *MockPullRequests_AddReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Reviewers))
	})
	return _c
}

func (_c *MockPullRequests_AddReviewers_Call) Return(_a0 error) *MockPullRequests_AddReviewers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPullRequests_AddReviewers_Call) RunAndReturn(run func(context.Context, []models.Reviewers) error) *MockPullRequests_AddReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, pr
func (_m *MockPullRequests) Create(ctx context.Context, pr *models.PullRequests) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequests) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPullRequests_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequests_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequests
func (_e *MockPullRequests_Expecter) Create(ctx interface{}, pr interface{}) *MockPullRequests_Create_Call {
	return &MockPullRequests_Create_Call{Call: _e.mock.On("Create", ctx, pr)}
}

func (_c *MockPullRequests_Create_Call) Run(run func(ctx context.Context, pr *models.PullRequests)) *MockPullRequests_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequests))
	})
	return _c
}

func (_c *MockPullRequests_Create_Call) Return(_a0 error) *MockPullRequests_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPullRequests_Create_Call) RunAndReturn(run func(context.Context, *models.PullRequests) error) *MockPullRequests_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPullRequests) GetByID(ctx context.Context, id uuid.UUID) (*models.PullRequests, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.PullRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PullRequests, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PullRequests); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequests_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPullRequests_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPullRequests_Expecter) GetByID(ctx interface{}, id interface{}) *MockPullRequests_GetByID_Call {
	return &MockPullRequests_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPullRequests_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPullRequests_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPullRequests_GetByID_Call) Return(_a0 *models.PullRequests, _a1 error) *MockPullRequests_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequests_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PullRequests, error)) *MockPullRequests_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *MockPullRequests) GetByReviewer(ctx context.Context, reviewerID uuid.UUID) ([]models.PullRequests, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewer")
	}

	var r0 []models.PullRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PullRequests, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PullRequests); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PullRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequests_GetByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReviewer'
type MockPullRequests_GetByReviewer_Call struct {
	*mock.Call
}

// GetByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID uuid.UUID
func (_e *MockPullRequests_Expecter) GetByReviewer(ctx interface{}, reviewerID interface{}) *MockPullRequests_GetByReviewer_Call {
	return &MockPullRequests_GetByReviewer_Call{Call: _e.mock.On("GetByReviewer", ctx, reviewerID)}
}

func (_c *MockPullRequests_GetByReviewer_Call) Run(run func(ctx context.Context, reviewerID uuid.UUID)) *MockPullRequests_GetByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPullRequests_GetByReviewer_Call) Return(_a0 []models.PullRequests, _a1 error) *MockPullRequests_GetByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequests_GetByReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.PullRequests, error)) *MockPullRequests_GetByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewers provides a mock function with given fields: ctx, prID
func (_m *MockPullRequests) GetReviewers(ctx context.Context, prID uuid.UUID) ([]models.Reviewers, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewers")
	}

	var r0 []models.Reviewers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Reviewers, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Reviewers); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reviewers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequests_GetReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewers'
type MockPullRequests_GetReviewers_Call struct {
	*mock.Call
}

// GetReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
func (_e *MockPullRequests_Expecter) GetReviewers(ctx interface{}, prID interface{}) *MockPullRequests_GetReviewers_Call {
	return &MockPullRequests_GetReviewers_Call{Call: _e.mock.On("GetReviewers", ctx, prID)}
}

func (_c *MockPullRequests_GetReviewers_Call) Run(run func(ctx context.Context, prID uuid.UUID)) *MockPullRequests_GetReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPullRequests_GetReviewers_Call) Return(_a0 []models.Reviewers, _a1 error) *MockPullRequests_GetReviewers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequests_GetReviewers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Reviewers, error)) *MockPullRequests_GetReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceReviewer provides a mock function with given fields: ctx, prID, oldID, newID
func (_m *MockPullRequests) ReplaceReviewer(ctx context.Context, prID uuid.UUID, oldID uuid.UUID, newID uuid.UUID) error {
	ret := _m.Called(ctx, prID, oldID, newID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, prID, oldID, newID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPullRequests_ReplaceReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceReviewer'
type MockPullRequests_ReplaceReviewer_Call struct {
	*mock.Call
}

// ReplaceReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - oldID uuid.UUID
//   - newID uuid.UUID
func (_e *MockPullRequests_Expecter) ReplaceReviewer(ctx interface{}, prID interface{}, oldID interface{}, newID interface{}) *MockPullRequests_ReplaceReviewer_Call {
	return &MockPullRequests_ReplaceReviewer_Call{Call: _e.mock.On("ReplaceReviewer", ctx, prID, oldID, newID)}
}

func (_c *MockPullRequests_ReplaceReviewer_Call) Run(run func(ctx context.Context, prID uuid.UUID, oldID uuid.UUID, newID uuid.UUID)) *MockPullRequests_ReplaceReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockPullRequests_ReplaceReviewer_Call) Return(_a0 error) *MockPullRequests_ReplaceReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPullRequests_ReplaceReviewer_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockPullRequests_ReplaceReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, pr
func (_m *MockPullRequests) Update(ctx context.Context, pr *models.PullRequests) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequests) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPullRequests_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPullRequests_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequests
func (_e *MockPullRequests_Expecter) Update(ctx interface{}, pr interface{}) *MockPullRequests_Update_Call {
	return &MockPullRequests_Update_Call{Call: _e.mock.On("Update", ctx, pr)}
}

func (_c *MockPullRequests_Update_Call) Run(run func(ctx context.Context, pr *models.PullRequests)) *MockPullRequests_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequests))
	})
	return _c
}

func (_c *MockPullRequests_Update_Call) Return(_a0 error) *MockPullRequests_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPullRequests_Update_Call) RunAndReturn(run func(context.Context, *models.PullRequests) error) *MockPullRequests_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPullRequests creates a new instance of MockPullRequests. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequests(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequests {
	mock := &MockPullRequests{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
