// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "mPR/internal/pkg/storage/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTeams is an autogenerated mock type for the Teams type
type MockTeams struct {
	mock.Mock
}

type MockTeams_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeams) EXPECT() *MockTeams_Expecter {
	return &MockTeams_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, team
func (_m *MockTeams) Create(ctx context.Context, team *models.Teams) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Teams) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeams_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeams_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Teams
func (_e *MockTeams_Expecter) Create(ctx interface{}, team interface{}) *MockTeams_Create_Call {
	return &MockTeams_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *MockTeams_Create_Call) Run(run func(ctx context.Context, team *models.Teams)) *MockTeams_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Teams))
	})
	return _c
}

func (_c *MockTeams_Create_Call) Return(_a0 error) *MockTeams_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeams_Create_Call) RunAndReturn(run func(context.Context, *models.Teams) error) *MockTeams_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockTeams) GetByName(ctx context.Context, name string) (*models.Teams, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Teams
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Teams, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Teams); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Teams)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeams_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeams_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeams_Expecter) GetByName(ctx interface{}, name interface{}) *MockTeams_GetByName_Call {
	return &MockTeams_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTeams_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTeams_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeams_GetByName_Call) Return(_a0 *models.Teams, _a1 error) *MockTeams_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeams_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.Teams, error)) *MockTeams_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeams creates a new instance of MockTeams. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeams(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeams {
	mock := &MockTeams{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
